services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  TorqIT\ObjectLayoutGridBundle\Webpack\WebpackEntryPointProvider:
    tags:
      - { name: "pimcore_studio_ui.webpack_entry_point_provider" }
